# Generated by Django 3.2.7 on 2021-11-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_image',
            field=models.ImageField(upload_to='lot_images'),
        ),
    ]
