# Generated by Django 3.2.7 on 2021-11-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
