# Generated by Django 3.2.7 on 2021-11-22 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_bid_bid_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_price',
            new_name='bid_value',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bid_lot_id',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='lot_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='lotbid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.lot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lot',
            name='lot_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
