# Generated by Django 3.2.7 on 2021-11-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20211122_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
