# Generated by Django 3.2.9 on 2021-11-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20211122_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='lot_description',
            field=models.CharField(max_length=70),
        ),
    ]
